version: '3.9'

networks:
  webapp:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
        - "8000:80"
        links:
        - php
        volumes:
        - ./:/var/www/html
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
        depends_on:
        - php
        - postgres
        networks:
        - webapp
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
        - ./:/var/www/html
        ports:
        - "9001:9000"
        networks:
        - webapp

    postgres:
        image: postgres:8
        container_name: postgres
        restart: on-failure
        ports:
        - "5433:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 
            POSTGRES_DB: postgres
            
        networks:
        - webapp
